# Generated by Django 5.2.7 on 2025-10-17 15:47

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Principal loan amount in EUR",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual percentage rate- APR",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "loan_term",
                    models.IntegerField(
                        help_text="Loan term in months",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Calculated monthly payment amount",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("DISBURSED", "Disbursed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user (installer) who created this loan offer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_offers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_offers",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Offer",
                "verbose_name_plural": "Loan Offers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "status"],
                        name="loans_loano_custome_d5d6eb_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="loans_loano_created_69f029_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="loans_loano_status_bf29e8_idx",
                    ),
                    models.Index(
                        fields=["created_by", "created_at"],
                        name="loans_loano_created_53ebc7_idx",
                    ),
                ],
            },
        ),
    ]
